# Generated by Django 4.0.1 on 2022-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_Name', models.CharField(max_length=100)),
                ('m_Email', models.CharField(max_length=100)),
                ('m_Subject', models.CharField(max_length=100)),
                ('m_Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
